name: ClaudeOnTheWebDemo

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"

targets:
  ClaudeOnTheWebDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ClaudeOnTheWebDemo
    scheme:
      testTargets: []
