name: ClaudeOnTheWebDemo

options:
  deploymentTarget:
    iOS: "17.0"
  bundleIdPrefix: com.example

targets:
  ClaudeOnTheWebDemo:
    type: application
    platform: iOS
    sources:
      - ClaudeOnTheWebDemo
    info:
      path: ClaudeOnTheWebDemo/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.ClaudeOnTheWebDemo
      SWIFT_VERSION: "5.0"
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      TARGETED_DEVICE_FAMILY: "1"
