name: HelloWorld

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

targets:
  HelloWorld:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        SWIFT_VERSION: "5.9"
        PRODUCT_BUNDLE_IDENTIFIER: com.example.HelloWorld
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
